# Generated by Django 3.2 on 2023-11-27 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
        ('users', '0002_auto_20231127_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='auditorium_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Auditoriums_for_teachers_lecture', to='Project.auditorium', verbose_name='Birinji sagat okatmaly auditorýasy'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='auditorium_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Auditoriums_for_teachers_lecture_2', to='Project.auditorium', verbose_name='Ikinji sagat okatmaly auditorýasy'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='auditorium_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Auditoriums_for_teachers_lecture_3', to='Project.auditorium', verbose_name='Üçünji sagat okatmaly auditorýasy'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='group_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Groups_for_teachers_lecture', to='Project.group', verbose_name='Birinji sagat okatmaly topary'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='group_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Groups_for_teachers_lecture_2', to='Project.group', verbose_name='Ikinji sagat okatmaly topary'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='group_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Groups_for_teachers_lecture_3', to='Project.group', verbose_name='Üçünji sagat okatmaly topary'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='lecture_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lectures_for_teachers_lecture', to='Project.lecture', verbose_name='Birinji sagat okatmaly dersi'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='lecture_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lectures_for_teachers_lecture_2', to='Project.lecture', verbose_name='Ikinji sagat okatmaly dersi'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='lecture_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lectures_for_teachers_lecture_3', to='Project.lecture', verbose_name='Üçünji sagat okatmaly dersi'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manual',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Degree_for_teachers', to='Project.degree', verbose_name='Mugallym derejesi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Department_for_teachers', to='Project.department', verbose_name='Mugallym kafedrasy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lectures',
            field=models.ManyToManyField(to='Project.Lecture', verbose_name='Mugallym okatýan dersleri'),
        ),
        migrations.AlterField(
            model_name='video',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
