# Generated by Django 3.2 on 2023-11-28 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20231128_1129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sagbol',
        ),
        migrations.DeleteModel(
            name='salam',
        ),
    ]
