# Generated by Django 3.2 on 2023-11-29 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_barkod_san'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=100)),
        ),
        migrations.AddField(
            model_name='video',
            name='view',
            field=models.IntegerField(default=1),
        ),
    ]
