# Generated by Django 3.2 on 2023-11-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20231129_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
