# Generated by Django 3.2 on 2023-11-29 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_video_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
