# Generated by Django 3.2 on 2023-11-27 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Auditoriýa no')),
            ],
            options={
                'verbose_name_plural': 'Auditorýalar',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Dereje')),
            ],
            options={
                'verbose_name_plural': 'Derejeler',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kafedra')),
            ],
            options={
                'verbose_name_plural': 'Kafedralar',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='Topar no')),
            ],
            options={
                'verbose_name_plural': 'Toparlar',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ders ady')),
                ('icon', models.ImageField(upload_to='Lecture_image', verbose_name='Ders suraty')),
            ],
            options={
                'verbose_name_plural': 'Dersler',
            },
        ),
    ]
