# Generated by Django 3.2 on 2023-11-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_alter_teacher_manuals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_image',
            field=models.ImageField(upload_to='manuals/'),
        ),
    ]
