# Generated by Django 3.2 on 2023-11-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_alter_teacher_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='video',
            field=models.FileField(upload_to='manuals/'),
        ),
    ]
