# Generated by Django 3.2 on 2023-11-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_alter_teacher_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='manuals',
            field=models.FileField(upload_to='manuals'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='video',
            field=models.FileField(upload_to='videos'),
        ),
    ]
