# Generated by Django 3.2 on 2023-11-14 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Project', '0006_auto_20231114_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('teacher_image', models.ImageField(upload_to='images')),
                ('video', models.FileField(upload_to='videos')),
                ('manuals', models.FileField(upload_to='manuals')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Degree_for_teachers', to='Project.degree')),
                ('lectures', models.ManyToManyField(to='Project.Lecture')),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='lectures',
        ),
        migrations.DeleteModel(
            name='Daily',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
