# Generated by Django 3.2 on 2023-11-16 05:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_daily'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='daily',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lectures_for_teachers_lecture', to='Project.lecture'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='auditorium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Auditoriums_for_teachers_lecture', to='Project.auditorium'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Groups_for_teachers_lecture', to='Project.group'),
        ),
    ]
