# Generated by Django 3.2 on 2023-11-24 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0010_rename_userprofile_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='video',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.teacher')),
            ],
        ),
    ]
